# Generated by Django 3.1.1 on 2020-10-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderdetail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Submitted', 'Order Submitted'), ('Order Processing', 'Order Processing'), ('Order Preparing', 'Order Preparing'), ('Order on its way', 'Order on its way')], default='Order Submitted', max_length=50),
        ),
    ]
