# Generated by Django 3.1.1 on 2020-10-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='money',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Submitted', 'Order Submitted'), ('Order Processing', 'Order Processing'), ('Order Preparing', 'Order Preparing'), ('Order on its way', 'Order on its way')], default='Order Submitted', max_length=100),
        ),
    ]
